version: '3.1'

volumes:
    uploads: { }
    db: { }

services:
    mongo:
        image: mongo
        expose:
            - "27017"
        restart: unless-stopped
        volumes:
            - db:/data/db

    server:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - 'mongo'
        ports:
            - "3000:3000"
            - "10000:10000"
        volumes:
            #- ./src:/app/src/:consistent
            #- ./static:/app/static/:ro
            - uploads:/app/uploads