version: '3.1'

volumes:
    uploads: {}
    db: {}
    static: {}
    src: {}

services:
    mongo:
        image: mongo
        expose:
            - "27017"
        restart: unless-stopped
        volumes:
            - db:/data/db

    sync:
        build: docker/sync
        restart: unless-stopped
        volumes:
            - ./src:/dev/src/:consistent
            - ./static:/dev/static/:ro
            - src:/app/src
            - static:/app/static


    server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        depends_on:
            - 'mongo'
        ports:
            - "3000:3000"
            - "10000:10000"
        volumes:
            - uploads:/app/uploads
            - src:/app/src
            - static:/app/static